Catch ValueError from signature.
This can happen if a signature cannot be provided
see https://docs.python.org/3/library/inspect.html
In my case this caused the docs build to error with:

ValueError: callable operator.itemgetter(2) is not supported by
signature